"""empty message

Revision ID: 238de447f4ee
Revises: a17843f2ceed
Create Date: 2023-10-21 14:22:24.449005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '238de447f4ee'
down_revision = 'a17843f2ceed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_column('picture')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('picture', sa.BLOB(), nullable=True))

    # ### end Alembic commands ###
